import mongoose from "mongoose";
import { connectDB } from "@/lib/db";
import { Course } from "@/models/Course";

// ─── Seed Data ────────────────────────────────────────────────────────────────

const courses = [
  // ── Web Development ──────────────────────────────────────────────────────
  {
    title: "The Complete HTML & CSS Bootcamp",
    description:
      "Master HTML5 and CSS3 from scratch. Build responsive, modern websites using Flexbox, Grid, and animations.",
    category: "Web Development",
    subcategory: "Frontend",
    instructor: "Sarah Mitchell",
    price: 1299,
    discountPrice: 499,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=HTML+CSS",
    rating: 4.7,
    totalRatings: 18420,
    totalStudents: 94300,
    duration: 28,
    lessons: [],
    tags: ["html", "css", "web design", "frontend", "responsive"],
    isPublished: true,
  },
  {
    title: "JavaScript: The Complete Guide 2024",
    description:
      "Deep dive into modern JavaScript — ES6+, async/await, the DOM, OOP, and functional programming patterns.",
    category: "Web Development",
    subcategory: "Frontend",
    instructor: "James Forrest",
    price: 1499,
    discountPrice: 599,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=JavaScript",
    rating: 4.8,
    totalRatings: 32100,
    totalStudents: 158000,
    duration: 52,
    lessons: [],
    tags: ["javascript", "es6", "dom", "async", "oop"],
    isPublished: true,
  },
  {
    title: "React — The Complete Developer Guide",
    description:
      "Build powerful SPAs with React 18. Covers hooks, Context API, Redux Toolkit, React Query, and Next.js basics.",
    category: "Web Development",
    subcategory: "Frontend",
    instructor: "Priya Sharma",
    price: 1599,
    discountPrice: 649,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=React",
    rating: 4.8,
    totalRatings: 27500,
    totalStudents: 121000,
    duration: 48,
    lessons: [],
    tags: ["react", "hooks", "redux", "spa", "frontend"],
    isPublished: true,
  },
  {
    title: "Node.js & Express — Backend Mastery",
    description:
      "Build scalable REST APIs and real-time apps with Node.js, Express, MongoDB, and JWT authentication.",
    category: "Web Development",
    subcategory: "Backend",
    instructor: "Carlos Mendes",
    price: 1499,
    discountPrice: 599,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=NodeJS",
    rating: 4.6,
    totalRatings: 14200,
    totalStudents: 67400,
    duration: 38,
    lessons: [],
    tags: ["nodejs", "express", "rest api", "mongodb", "backend"],
    isPublished: true,
  },
  {
    title: "Full-Stack MERN Bootcamp",
    description:
      "Build full-stack apps end-to-end with MongoDB, Express, React, and Node.js including deployment on AWS.",
    category: "Web Development",
    subcategory: "Full Stack",
    instructor: "Anjali Verma",
    price: 1999,
    discountPrice: 799,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=MERN",
    rating: 4.7,
    totalRatings: 19800,
    totalStudents: 88000,
    duration: 64,
    lessons: [],
    tags: ["mern", "mongodb", "express", "react", "nodejs"],
    isPublished: true,
  },
  {
    title: "Next.js 14 — Full Stack Framework",
    description:
      "Master Next.js App Router, Server Components, Server Actions, middleware, and full-stack patterns.",
    category: "Web Development",
    subcategory: "Full Stack",
    instructor: "Tom Eriksson",
    price: 1699,
    discountPrice: 699,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=NextJS",
    rating: 4.8,
    totalRatings: 11200,
    totalStudents: 52000,
    duration: 40,
    lessons: [],
    tags: ["nextjs", "react", "server components", "app router"],
    isPublished: true,
  },
  {
    title: "TypeScript: From Zero to Pro",
    description:
      "Everything about TypeScript — types, interfaces, generics, decorators, and integrating with React and Node.",
    category: "Web Development",
    subcategory: "Frontend",
    instructor: "Lena Bauer",
    price: 1299,
    discountPrice: 549,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=TypeScript",
    rating: 4.7,
    totalRatings: 9800,
    totalStudents: 44000,
    duration: 30,
    lessons: [],
    tags: ["typescript", "javascript", "generics", "types"],
    isPublished: true,
  },

  // ── Data Science & Machine Learning ──────────────────────────────────────
  {
    title: "Python for Data Science & Machine Learning",
    description:
      "Learn NumPy, Pandas, Matplotlib, Seaborn, Scikit-Learn, and build real ML models from scratch.",
    category: "Data Science",
    subcategory: "Machine Learning",
    instructor: "Dr. Arjun Patel",
    price: 1799,
    discountPrice: 749,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Data+Science",
    rating: 4.8,
    totalRatings: 41000,
    totalStudents: 192000,
    duration: 60,
    lessons: [],
    tags: ["python", "machine learning", "pandas", "numpy", "scikit-learn"],
    isPublished: true,
  },
  {
    title: "Deep Learning with TensorFlow & Keras",
    description:
      "Build neural networks, CNNs, RNNs, and transformers. Train models on real datasets and deploy them.",
    category: "Data Science",
    subcategory: "Deep Learning",
    instructor: "Mei Lin",
    price: 1999,
    discountPrice: 849,
    level: "Advanced",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Deep+Learning",
    rating: 4.7,
    totalRatings: 22100,
    totalStudents: 98000,
    duration: 55,
    lessons: [],
    tags: ["deep learning", "tensorflow", "keras", "neural networks", "cnn"],
    isPublished: true,
  },
  {
    title: "Data Analysis with Python & SQL",
    description:
      "Analyze real-world datasets using Python, Pandas, and SQL. Create dashboards with Plotly and Dash.",
    category: "Data Science",
    subcategory: "Data Analysis",
    instructor: "Fatima Al-Rashid",
    price: 1499,
    discountPrice: 599,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Data+Analysis",
    rating: 4.6,
    totalRatings: 13500,
    totalStudents: 61000,
    duration: 36,
    lessons: [],
    tags: ["python", "sql", "pandas", "data analysis", "plotly"],
    isPublished: true,
  },
  {
    title: "Natural Language Processing with Python",
    description:
      "Build NLP pipelines with NLTK, spaCy, and HuggingFace Transformers for text classification, summarization, and more.",
    category: "Data Science",
    subcategory: "NLP",
    instructor: "Dr. Arjun Patel",
    price: 1799,
    discountPrice: 749,
    level: "Advanced",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=NLP",
    rating: 4.7,
    totalRatings: 8600,
    totalStudents: 38000,
    duration: 42,
    lessons: [],
    tags: ["nlp", "transformers", "huggingface", "spacy", "text classification"],
    isPublished: true,
  },

  // ── Mobile Development ───────────────────────────────────────────────────
  {
    title: "React Native — Build iOS & Android Apps",
    description:
      "Create cross-platform mobile apps with React Native, Expo, navigation, state management, and native APIs.",
    category: "Mobile Development",
    subcategory: "Cross Platform",
    instructor: "Priya Sharma",
    price: 1599,
    discountPrice: 649,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=React+Native",
    rating: 4.6,
    totalRatings: 14900,
    totalStudents: 68000,
    duration: 44,
    lessons: [],
    tags: ["react native", "expo", "mobile", "ios", "android"],
    isPublished: true,
  },
  {
    title: "Flutter & Dart — Complete Mobile Dev Course",
    description:
      "Build beautiful native apps for iOS and Android using Flutter. Covers state management, Firebase, and deployment.",
    category: "Mobile Development",
    subcategory: "Cross Platform",
    instructor: "Omar Hassan",
    price: 1699,
    discountPrice: 699,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Flutter",
    rating: 4.7,
    totalRatings: 17200,
    totalStudents: 79000,
    duration: 46,
    lessons: [],
    tags: ["flutter", "dart", "firebase", "mobile", "cross-platform"],
    isPublished: true,
  },
  {
    title: "iOS Development with Swift & SwiftUI",
    description:
      "Build production-ready iOS apps with Swift 5, SwiftUI, Core Data, and publish to the App Store.",
    category: "Mobile Development",
    subcategory: "iOS",
    instructor: "Lena Bauer",
    price: 1799,
    discountPrice: 749,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=SwiftUI",
    rating: 4.7,
    totalRatings: 11800,
    totalStudents: 53000,
    duration: 50,
    lessons: [],
    tags: ["swift", "swiftui", "ios", "xcode", "apple"],
    isPublished: true,
  },

  // ── Cloud & DevOps ────────────────────────────────────────────────────────
  {
    title: "AWS Certified Solutions Architect — Associate",
    description:
      "Pass the AWS SAA-C03 exam. Covers EC2, S3, RDS, Lambda, VPC, IAM, and hands-on labs.",
    category: "Cloud Computing",
    subcategory: "AWS",
    instructor: "Carlos Mendes",
    price: 1999,
    discountPrice: 799,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=AWS",
    rating: 4.8,
    totalRatings: 28400,
    totalStudents: 132000,
    duration: 54,
    lessons: [],
    tags: ["aws", "cloud", "solutions architect", "ec2", "s3"],
    isPublished: true,
  },
  {
    title: "Docker & Kubernetes — The Practical Guide",
    description:
      "Containerize apps with Docker, orchestrate with Kubernetes, and deploy on cloud clusters with Helm.",
    category: "Cloud Computing",
    subcategory: "DevOps",
    instructor: "Tom Eriksson",
    price: 1699,
    discountPrice: 699,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Docker+K8s",
    rating: 4.7,
    totalRatings: 16300,
    totalStudents: 74000,
    duration: 38,
    lessons: [],
    tags: ["docker", "kubernetes", "devops", "containers", "helm"],
    isPublished: true,
  },
  {
    title: "CI/CD with GitHub Actions & Jenkins",
    description:
      "Build automated pipelines — from code commit to production deployment — using GitHub Actions and Jenkins.",
    category: "Cloud Computing",
    subcategory: "DevOps",
    instructor: "Anjali Verma",
    price: 1299,
    discountPrice: 549,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=CICD",
    rating: 4.5,
    totalRatings: 7400,
    totalStudents: 33000,
    duration: 26,
    lessons: [],
    tags: ["cicd", "github actions", "jenkins", "devops", "automation"],
    isPublished: true,
  },

  // ── Cybersecurity ─────────────────────────────────────────────────────────
  {
    title: "Ethical Hacking & Penetration Testing",
    description:
      "Learn offensive security — reconnaissance, exploitation, post-exploitation, and writing pentest reports.",
    category: "Cybersecurity",
    subcategory: "Ethical Hacking",
    instructor: "Marcus Webb",
    price: 1799,
    discountPrice: 749,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Ethical+Hacking",
    rating: 4.7,
    totalRatings: 21000,
    totalStudents: 95000,
    duration: 48,
    lessons: [],
    tags: ["ethical hacking", "penetration testing", "kali linux", "security"],
    isPublished: true,
  },
  {
    title: "CompTIA Security+ Certification Prep",
    description:
      "Complete prep for SY0-701. Covers threats, architecture, cryptography, identity management, and compliance.",
    category: "Cybersecurity",
    subcategory: "Certification",
    instructor: "Fatima Al-Rashid",
    price: 1599,
    discountPrice: 649,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Security%2B",
    rating: 4.6,
    totalRatings: 12700,
    totalStudents: 57000,
    duration: 32,
    lessons: [],
    tags: ["comptia", "security+", "certification", "cybersecurity"],
    isPublished: true,
  },

  // ── Design ────────────────────────────────────────────────────────────────
  {
    title: "UI/UX Design Masterclass with Figma",
    description:
      "Design stunning interfaces and prototypes in Figma. Learn design systems, user research, and usability testing.",
    category: "Design",
    subcategory: "UI/UX",
    instructor: "Nadia Petrova",
    price: 1499,
    discountPrice: 599,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=UX+Design",
    rating: 4.8,
    totalRatings: 24600,
    totalStudents: 111000,
    duration: 36,
    lessons: [],
    tags: ["figma", "ui design", "ux", "prototyping", "design systems"],
    isPublished: true,
  },
  {
    title: "Graphic Design Bootcamp — Photoshop & Illustrator",
    description:
      "Master Adobe Photoshop and Illustrator for logos, branding, social media graphics, and print design.",
    category: "Design",
    subcategory: "Graphic Design",
    instructor: "Ricardo Vega",
    price: 1399,
    discountPrice: 549,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Graphic+Design",
    rating: 4.6,
    totalRatings: 16800,
    totalStudents: 76000,
    duration: 34,
    lessons: [],
    tags: ["photoshop", "illustrator", "graphic design", "branding", "adobe"],
    isPublished: true,
  },
  {
    title: "Motion Graphics with After Effects",
    description:
      "Create professional animations, motion graphics, and visual effects for video content and ads.",
    category: "Design",
    subcategory: "Motion Graphics",
    instructor: "Nadia Petrova",
    price: 1499,
    discountPrice: 599,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=After+Effects",
    rating: 4.6,
    totalRatings: 9200,
    totalStudents: 42000,
    duration: 30,
    lessons: [],
    tags: ["after effects", "motion graphics", "animation", "vfx", "adobe"],
    isPublished: true,
  },

  // ── Business & Entrepreneurship ───────────────────────────────────────────
  {
    title: "The Complete Digital Marketing Course",
    description:
      "Master SEO, Google Ads, Facebook Ads, email marketing, content strategy, and analytics in one course.",
    category: "Business",
    subcategory: "Digital Marketing",
    instructor: "James Forrest",
    price: 1499,
    discountPrice: 599,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Digital+Marketing",
    rating: 4.6,
    totalRatings: 29000,
    totalStudents: 134000,
    duration: 40,
    lessons: [],
    tags: ["seo", "google ads", "facebook ads", "email marketing", "analytics"],
    isPublished: true,
  },
  {
    title: "Startup Fundamentals — From Idea to Launch",
    description:
      "Build and launch a startup — idea validation, MVP, fundraising, growth hacking, and pitching to investors.",
    category: "Business",
    subcategory: "Entrepreneurship",
    instructor: "Marcus Webb",
    price: 1299,
    discountPrice: 499,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Startup",
    rating: 4.5,
    totalRatings: 10400,
    totalStudents: 48000,
    duration: 24,
    lessons: [],
    tags: ["startup", "entrepreneurship", "mvp", "fundraising", "pitch"],
    isPublished: true,
  },
  {
    title: "Financial Modeling & Valuation in Excel",
    description:
      "Build DCF models, LBO models, and comparable company analysis used by investment bankers and analysts.",
    category: "Business",
    subcategory: "Finance",
    instructor: "Fatima Al-Rashid",
    price: 1799,
    discountPrice: 749,
    level: "Intermediate",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Financial+Modeling",
    rating: 4.7,
    totalRatings: 13200,
    totalStudents: 59000,
    duration: 30,
    lessons: [],
    tags: ["excel", "financial modeling", "dcf", "valuation", "finance"],
    isPublished: true,
  },

  // ── Personal Development ──────────────────────────────────────────────────
  {
    title: "Public Speaking & Presentation Mastery",
    description:
      "Overcome fear, structure compelling talks, and deliver with confidence in any professional setting.",
    category: "Personal Development",
    subcategory: "Communication",
    instructor: "Sarah Mitchell",
    price: 999,
    discountPrice: 399,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Public+Speaking",
    rating: 4.7,
    totalRatings: 18700,
    totalStudents: 86000,
    duration: 14,
    lessons: [],
    tags: ["public speaking", "presentation", "communication", "confidence"],
    isPublished: true,
  },
  {
    title: "Productivity Mastery — Deep Work & Time Management",
    description:
      "Build systems for focused work, eliminate distractions, and 10x your output using proven frameworks.",
    category: "Personal Development",
    subcategory: "Productivity",
    instructor: "Ricardo Vega",
    price: 899,
    discountPrice: 349,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Productivity",
    rating: 4.5,
    totalRatings: 12100,
    totalStudents: 55000,
    duration: 12,
    lessons: [],
    tags: ["productivity", "time management", "deep work", "habits", "focus"],
    isPublished: true,
  },

  // ── Photography & Video ───────────────────────────────────────────────────
  {
    title: "Photography Masterclass — Complete Guide",
    description:
      "Go from auto mode to manual mastery. Covers composition, lighting, editing in Lightroom, and building a portfolio.",
    category: "Photography",
    subcategory: "Photography",
    instructor: "Omar Hassan",
    price: 1199,
    discountPrice: 499,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Photography",
    rating: 4.7,
    totalRatings: 21500,
    totalStudents: 98000,
    duration: 26,
    lessons: [],
    tags: ["photography", "lightroom", "composition", "dslr", "editing"],
    isPublished: true,
  },
  {
    title: "Video Editing with Premiere Pro",
    description:
      "Edit professional-quality videos — cuts, color grading, audio mixing, captions, and YouTube optimization.",
    category: "Photography",
    subcategory: "Video Editing",
    instructor: "Mei Lin",
    price: 1299,
    discountPrice: 549,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Premiere+Pro",
    rating: 4.6,
    totalRatings: 14700,
    totalStudents: 67000,
    duration: 22,
    lessons: [],
    tags: ["premiere pro", "video editing", "color grading", "youtube", "adobe"],
    isPublished: true,
  },

  // ── Language Learning ─────────────────────────────────────────────────────
  {
    title: "Spanish for Beginners — A Complete Course",
    description:
      "Learn conversational Spanish from zero — grammar, vocabulary, listening, and speaking through real dialogues.",
    category: "Language Learning",
    subcategory: "Spanish",
    instructor: "Carlos Mendes",
    price: 999,
    discountPrice: 399,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Spanish",
    rating: 4.6,
    totalRatings: 16200,
    totalStudents: 74000,
    duration: 18,
    lessons: [],
    tags: ["spanish", "language learning", "beginner", "grammar", "speaking"],
    isPublished: true,
  },
  {
    title: "Japanese for Beginners — Hiragana to Conversation",
    description:
      "Start from zero and reach conversational level. Covers Hiragana, Katakana, Kanji basics, and JLPT N5 prep.",
    category: "Language Learning",
    subcategory: "Japanese",
    instructor: "Mei Lin",
    price: 1099,
    discountPrice: 449,
    level: "Beginner",
    language: "English",
    thumbnail: "https://placehold.co/600x400?text=Japanese",
    rating: 4.7,
    totalRatings: 11300,
    totalStudents: 51000,
    duration: 20,
    lessons: [],
    tags: ["japanese", "hiragana", "katakana", "jlpt", "language learning"],
    isPublished: true,
  },
];

// ─── Seeder ────────────────────────────────────────────────────────────────

async function seed() {
  try {
    await connectDB();
    console.log("✅ Connected to database");

    const existing = await Course.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  Database already has ${existing} courses.`);
      console.log("   Delete existing records first, or set FORCE_SEED=true to override.");

      if (process.env.FORCE_SEED !== "true") {
        process.exit(0);
      }

      await Course.deleteMany({});
      console.log("🗑️  Cleared existing courses.");
    }

    const inserted = await Course.insertMany(courses);
    console.log(`🌱 Successfully seeded ${inserted.length} courses across categories:`);

    // Log summary by category
    const summary: Record<string, number> = {};
    for (const c of courses) {
      summary[c.category] = (summary[c.category] ?? 0) + 1;
    }
    for (const [cat, count] of Object.entries(summary)) {
      console.log(`   • ${cat}: ${count} course${count > 1 ? "s" : ""}`);
    }
  } catch (err) {
    console.error("❌ Seeding failed:", err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from database.");
  }
}

seed();